PLATFORM_IS_JELLYBEAN := 1
ifneq (, $(findstring 4.2., $(PLATFORM_VERSION)))
PLATFORM_IS_JELLYBEAN_MR1 := 1
endif
ifeq ($(PLATFORM_VERSION),JellyBeanMR2)
PLATFORM_IS_JELLYBEAN_MR1 := 1
PLATFORM_IS_JELLYBEAN_MR2 := 1
endif
