LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_NO_2ND_ARCH_MODULE_SUFFIX := true

include $(NVIDIA_BASE)
include $(BUILD_JAVA_LIBRARY)

# BUILD_JAVA_LIBRARY doesn't consider additional dependencies
$(LOCAL_BUILT_MODULE): $(LOCAL_ADDITIONAL_DEPENDENCIES)
LOCAL_NO_2ND_ARCH_MODULE_SUFFIX :=
