NVIDIA_NVMAKE_BUILD_TYPE :=
NVIDIA_NVMAKE_TOP :=
NVIDIA_NVMAKE_MODULE_NAME :=
NVIDIA_NVMAKE_VERBOSE :=
NVIDIA_NVMAKE_GUARDWORD :=
NVIDIA_NVMAKE_MODULE_PRIVATE_PATH :=
NVIDIA_NVMAKE_UNIX_BUILD_COMMAND :=
