
SAVED_MODULE := $(LOCAL_MODULE)
SAVED_SHARED_LIBRARIES := $(LOCAL_SHARED_LIBRARIES)
SAVED_STATIC_LIBRARIES := $(LOCAL_STATIC_LIBRARIES)
SAVED_LDFLAGS := $(LOCAL_LDFLAGS)
SAVED_NO_2ND_ARCH := $(LOCAL_NO_2ND_ARCH)
SAVED_32_BIT_ONLY := $(LOCAL_32_BIT_ONLY)
SAVED_MODULE_TARGET_ARCH := $(LOCAL_MODULE_TARGET_ARCH)
SAVED_MODULE_TARGET_ARCH_WARN := $(LOCAL_MODULE_TARGET_ARCH_WARN)
SAVED_MODULE_UNSUPPORTED_TARGET_ARCH := $(LOCAL_MODULE_UNSUPPORTED_TARGET_ARCH)
SAVED_MODULE_UNSUPPORTED_TARGET_ARCH_WARN := $(LOCAL_MODULE_UNSUPORTED_TARGET_ARCH_WARN)
SAVED_MAKEFILE := $(NVIDIA_MAKEFILE)

LOCAL_MODULE := $(LOCAL_MODULE)_static

include $(NVIDIA_STATIC_LIBRARY)

include $(NVIDIA_DEFAULTS)

NVIDIA_MAKEFILE := $(SAVED_MAKEFILE)
LOCAL_MODULE := $(SAVED_MODULE)
LOCAL_WHOLE_STATIC_LIBRARIES := $(SAVED_MODULE)_static
LOCAL_SHARED_LIBRARIES := $(SAVED_SHARED_LIBRARIES)
LOCAL_STATIC_LIBRARIES := $(SAVED_STATIC_LIBRARIES)
LOCAL_LDFLAGS := $(SAVED_LDFLAGS)
LOCAL_NO_2ND_ARCH := $(SAVED_NO_2ND_ARCH)
LOCAL_32_BIT_ONLY := $(SAVED_32_BIT_ONLY)
LOCAL_MODULE_TARGET_ARCH := $(SAVED_MODULE_TARGET_ARCH)
LOCAL_MODULE_TARGET_ARCH_WARN := $(SAVED_MODULE_TARGET_ARCH_WARN)
LOCAL_MODULE_UNSUPPORTED_TARGET_ARCH := $(SAVED_MODULE_UNSUPPORTED_TARGET_ARCH)
LOCAL_MODULE_UNSUPPORTED_TARGET_ARCH_WARN := $(SAVED_MODULE_UNSUPPORTED_TARGET_ARCH_WARN)

SAVED_MAKEFILE :=
SAVED_MODULE :=
SAVED_SHARED_LIBRARIES :=
SAVED_STATIC_LIBRARIES :=
SAVED_LDFLAGS :=
SAVED_NO_2ND_ARCH :=
SAVED_32_BIT_ONLY :=
SAVED_MODULE_TARGET_ARCH :=
SAVED_MODULE_TARGET_ARCH_WARN :=
SAVED_MODULE_UNSUPPORTED_TARGET_ARCH :=
SAVED_MODULE_UNSUPPORTED_TARGET_ARCH_WARN :=

include $(NVIDIA_SHARED_LIBRARY)



